### ISSUE TITLE
Use socket-io-client to connect serverSide with nodeJS server

### ISSUE THREAD

**Issue by mnaranjorion** [joncursi/socket-io-client#1]
Hi,
I'm testing socket-io-client to connect meteor with NodeJS server, but I cant achieve that my meteor server connect with my Node server. 
I declare my socket:
socket = io(IP_NODE);

I emit a message, 
socket.emit('register', {
                name : userName,
                age : userAge
            });
but in node server doesnt see anything.
¿What is wrong?

Thanks!!

**Comment by joncursi** [comment]
@mnaranjorion a couple pointers I'm able to give based on the limited information above:

1) When you declare the socket variable, you should do so with the following syntax: `var socket = io('https://address-goes-here/');`. Note the use of `var` to create a local variable, rather than global.

2) After `emit`, you should use the `on` method to connect to the NodeJS server. Note that this package is used to _receive_ data from the NoteJS server (subscribe), **not** send.

```
socket.on('connect', Meteor.bindEnvironment(function() {
  // do stuff
}, function(e) {
  throw e;
}));
```

Hope that helps shed some light.

**Comment by mnaranjorion** [comment]
Your help has been very useful.
Thanks!!!
